config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :events
  resources :venues
  resources :artists
  resources :categories
  resources :tickets

   root to: 'home#welcome'
    get '/welcome', to: 'home#welcome'
    get '/categories', to: 'home#categories'
    get '/events', to: 'home#events'
    get '/search', to: 'home#search'
    get '/venues', to: 'home#venues'
    get '/artists', to: 'home#artists '
    get '/Tickets', to: 'home#tickets'

end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :user
  belongs_to :event

  def availability(id)
    max_capacity - Ticket.booked(id)                   
  end
  
   def max_capacity  
     event.venue.capacity
   end
   
   
   def self.booked(id)
     where(event_id: id).count
   end

   

   def human_readable_date
     timetable_date.strftime('%A, %B %d %Y')
   end

   def human_readable_time
     timetable_date.strftime('%H:%M')
   end
   
  
  
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  #load_and_authorize_resource
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Ticket.all
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
    @events = Event.all
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(ticket_params.merge(user_id: current_user.id))

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'Ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def availability(id)
    max_capacity - Ticket.booked(id)                   
  end
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_params
      params.require(:ticket).permit(:event_id, :price)
    end
end

app/views/tickets/_form.html.erb
<%= form_for(@ticket) do |f| %>
  <% if @ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
      <% @ticket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :event_id %><br>
    <%= f.select(:event_id, Event.all.collect {|e| [ e.name, e.id ] }, {prompt: 'Select Event'}) %>
  </div>
  <div class="actions">
    <%= f.submit "Book Ticket!"%>
  </div>
<% end %>

app/views/tickets/edit.html.erb
<h1>Editing Ticket</h1>

<%= render 'form' %>

<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', tickets_path %>

app/views/tickets/index.html.erb
<p id="notice"><%= notice %></p>

<h1> Tickets</h1>

<table>
  <thead>
    <tr>
      <th>Event</th>
      <th>Venue</th>
      <th>Artist</th>
      <th>Time</th>
      <th>Date</th>
      <th>Tickets left</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tickets.each do |ticket| %>
      <tr>
        <td><%= ticket.event.name %></td>
        <td><%= ticket.event.venue.address %></td>
        <td><%= ticket.event.artist.name %></td>
        <td><%= ticket.event.human_readable_time %></td>
        <td><%= ticket.event.human_readable_date %></td>
        <td><%= ticket.availability(ticket.event.id) %></td>
        <td><%= link_to 'See details', ticket %></td>
        <td><%= link_to 'Edit', edit_ticket_path(ticket)  if can? :edit, ticket%></td>
        <td><%= link_to 'Destroy', ticket, method: :delete, data: { confirm: 'Are you sure?' } if can? :destroy, ticket%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ticket', new_ticket_path %>

app/views/tickets/new.html.erb
<h1>New Ticket</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Venue</th>
      <th>Artist</th>
      <th>Date</th>
      <th>Time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
      <td><%= image_tag event.event_image.medium.url %></td>
        <td><%= event.venue.address %></td>
        <td><%= event.artist.name %></td>
        <td><%= event.human_readable_time %></td>
        <td><%= event.human_readable_date %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= render 'form' %>

<%= link_to 'Back', tickets_path %>

app/views/tickets/show.html.erb
<p id="notice"><%= notice %></p>
  <p>
    <b>Image:</b>
    <%= link_to image_tag (@tickect.event_image.thumb.url) %>
</p>
<p>
  <strong>Event:</strong>
  <%= @ticket.event.name %>
</p>
<p>
  <strong>Venue:</strong>
  <%= @ticket.event.venue.address %>
</p>
<p>
  <strong>Artist:</strong>
  <%= @ticket.event.artist.name %>
</p>
 
<p>
  <strong>Date:</strong>
  <%= @ticket.event.human_readable_date %>
</p>
<p>
  <strong>Start Time:</strong>
  <%= @ticket.event.human_readable_time %>
</p>
<p>
  <strong>Price:</strong>
  <%= @ticket.event.price %>
</p>



<%= link_to 'Edit', edit_ticket_path(@ticket) %> |
<%= link_to 'Back', tickets_path %>